import { expect, test, type Page } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const base = "http://localhost:3000";
async function nav(page: Page, label: string) {
  const opener = page.getByRole("button", { name: /Open menu|Ouvrir le menu|فتح القائمة/ });
  if (await opener.isVisible()) await opener.click();
  await page.getByRole("navigation").getByRole("link", { name: label, exact: true }).click();
}
async function width(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
}
test("three profiles use the responsive FR/AR/EN shell and the offline correction journey", async ({ browser }) => {
  test.setTimeout(120000);
  const correctionText = "Phase 7 : préciser le résultat de la visite. " + new Date().toISOString();
  const evidence = Buffer.from("%PDF-1.4\nPhase 7 attachment through the translated mobile control.\n%%EOF");
  const errors: string[] = [];
  const author = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const reviewer = await browser.newContext({ viewport: { width: 1024, height: 768 } });
  const central = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const a = await author.newPage(), b = await reviewer.newPage(), c = await central.newPage();
  for (const page of [a,b,c]) page.on("pageerror", e => errors.push(e.message));
  for (const page of [a,b,c]) page.setDefaultTimeout(15000);
  await a.goto(base);
  await a.locator("#app-language").selectOption("en");
  await a.locator('[data-account="author_1"]').click();
  await expect(a.getByRole("heading", { name: "Your workspace" })).toBeVisible();
  await width(a);
  await nav(a,"Collection");
  const draftButton = a.locator("aside.panel").getByRole("button").filter({ hasText: /v1$/ }).first();
  await expect(draftButton).toBeVisible({ timeout: 30000 }); await draftButton.click();
  await a.getByLabel(/Report date/).fill(new Date().toISOString().slice(0,10));
  await a.getByLabel(/Situation level/).selectOption("0");
  await a.getByLabel(/Daily summary/).fill("Phase 7 shell report: complete author journey from the mobile English interface.");
  await a.getByRole("button", { name: /^Add —/ }).click();
  await a.getByLabel(/Category/).selectOption("0");
  await a.getByLabel(/Description/).fill("A field visit through the mobile interface.");
  await a.getByLabel(/Date and time/).fill(new Date().toISOString().slice(0,10)+"T08:30");
  await a.getByLabel(/Quantity/).fill("2");
  await a.getByLabel(/I confirm the accuracy/).check();
  console.log("author form prepared");
  await author.setOffline(true);
  await a.getByLabel("Add attachment").setInputFiles({ name: "preuve-phase7.pdf", mimeType: "application/pdf", buffer: evidence });
  await expect(a.getByText(/preuve-phase7.pdf/)).toBeVisible();
  await a.getByRole("button", { name: "Finalize report", exact: true }).click();
  await a.getByLabel("I have reviewed this report and confirm its content.").check();
  await a.getByRole("button", { name: "Confirm permanently", exact: true }).click();
  await expect(a.getByTestId("report-business-state")).toHaveText("Confirmed");
  await width(a);
  await a.screenshot({ path: path.resolve("../../.local/phase7-mobile.png"), fullPage: true });
  await author.setOffline(false);
  await expect(a.getByTestId("report-sync-state")).toHaveText("Report received by server", { timeout: 30000 });
  const originalHash = await a.getByTestId("report-hash").textContent();
  console.log("author report received");
  await b.goto(base);
  await b.locator('[data-account="reviewer"]').click();
  await nav(b,"Inbox");
  await expect(b.getByRole("heading", { name: /Rapport.*À examiner/ }).last()).toBeVisible({ timeout: 30000 });
  const row = b.locator("article.panel").filter({ hasText: "author_1" }).filter({ hasText: "À examiner" }).first();
  await row.getByRole("link", { name: "Consulter et commenter" }).click();
  await expect(b.locator(`main p[role="alert"]`)).toHaveCount(0);
  const fingerprint = b.locator("code").filter({ hasText: originalHash! });
  await expect(fingerprint).toBeVisible({ timeout: 30000 });
  await b.getByLabel("Commentaire", { exact: true }).fill("Phase 7 : revue depuis la tablette.");
  await b.getByRole("button", { name: "Ajouter le commentaire" }).click();
  await expect(b.getByText("Phase 7 : revue depuis la tablette.", { exact: true })).toBeVisible();
  const reportId = new URL(b.url()).searchParams.get("report")!;
  await b.getByLabel("Motif de correction").fill(correctionText);
  await b.getByRole("button", { name: "Demander une correction" }).click();
  await expect(b.getByRole("heading", { name: "Correction demandée" })).toBeVisible();
  await expect(b.getByRole("button", { name: "Préparer la nouvelle révision" })).toHaveCount(0);
  await width(b);
  console.log("reviewer correction requested");
  await nav(a,"Inbox");
  await expect(a.getByText(correctionText, { exact: false })).toBeVisible({ timeout: 30000 });
  await a.locator("#app-language").selectOption("ar");
  await expect(a.locator("html")).toHaveAttribute("dir", "rtl");
  await width(a);
  await author.setOffline(true); await a.reload();
  await expect(a.getByText(correctionText, { exact: false })).toBeVisible();
  await a.locator("article.panel").filter({ has: a.locator(`a[href="/reports?report=${reportId}"]`) }).getByRole("button", { name: "إعداد التصحيح دون اتصال" }).click();
  await expect(a.getByLabel(/ملخص اليوم/)).toBeVisible();
  await a.getByLabel(/ملخص اليوم/).fill("زيارة مكتملة مع تفاصيل النتيجة من الواجهة العربية دون اتصال.");
  await a.getByRole("button", { name: "إكمال التقرير", exact: true }).click();
  await a.getByLabel("راجعت هذا التقرير وأؤكد محتواه.").check();
  await a.getByRole("button", { name: "تأكيد نهائي", exact: true }).click();
  const correctedHash = await a.getByTestId("report-hash").textContent();
  await expect(a.getByTestId("report-business-state")).toHaveText("مؤكد");
  await width(a);
  await a.screenshot({ path: path.resolve("../../.local/phase7-arabic.png"), fullPage: true });
  await author.setOffline(false);
  // A hard offline reload drops the in-memory credential: reconnect through the normal login UI.
  await a.getByRole("button", { name: "تسجيل الخروج" }).click();
  await a.locator('[data-account="author_1"]').click();
  await expect(a.getByRole("button", { name: "إعداد نماذجي" })).toBeVisible();
  await expect(a.getByTestId("report-sync-state")).toHaveText("استلم الخادم التقرير", { timeout: 30000 });
  await nav(b,"Inbox");
  const reviewedRow = b.locator("article.panel").filter({ has: b.locator(`a[href="/reports?report=${reportId}"]`) });
  await expect(reviewedRow.getByRole("heading", { level: 2 })).toContainText("Corrigés", { timeout: 30000 });
  await reviewedRow.getByRole("button", { name: "Marquer comme examiné" }).click();
  await expect(reviewedRow.getByRole("heading", { level: 2 })).toContainText("Confirmé");
  console.log("corrected report received and reviewed");
  await c.goto(base); await c.locator("#app-language").selectOption("en");
  await c.locator('[data-account="central"]').click();
  await nav(c,"Reports");
  await c.locator("aside.panel").getByRole("button").filter({ hasText: reportId.slice(0,8) }).click();
  await expect(c.locator("code").filter({ hasText: originalHash! })).toBeVisible();
  await expect(c.locator("code").filter({ hasText: correctedHash! })).toBeVisible();
  await expect(c.getByRole("button", { name: /Add comment|Request correction|Prepare new revision/ })).toHaveCount(0);
  await expect(c.getByRole("navigation").getByRole("link", { name: /Collection|Forms|Administration/ })).toHaveCount(0);
  const downloadPromise = c.waitForEvent("download");
  await c.getByRole("button", { name: "Download preuve-phase7.pdf" }).first().click();
  const downloaded = await downloadPromise;
  expect(fs.readFileSync((await downloaded.path())!)).toEqual(evidence);
  await width(c);
  await c.screenshot({ path: path.resolve("../../.local/phase7-desktop.png"), fullPage: true });
  await c.locator("#app-language").selectOption("fr");
  await expect(c.getByRole("heading", { name: "Rapports confirmés" })).toBeVisible();
  expect(errors).toEqual([]);
  fs.writeFileSync(path.resolve("../../.local/phase7-gate.json"), JSON.stringify({ passed: true, originalHash, correctedHash,
    profiles: ["author","reviewer","central"], locales: ["fr","ar","en"], widths: [390,1024,1440], checked_at: new Date().toISOString() }, null, 2));
  await author.close(); await reviewer.close(); await central.close();
});
