import { test, expect } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const credentialsPath = path.resolve("../../.local/forms-demo.json");
test("published pilot: authorized API, FR/AR, groups, conditions and both validators", async ({ page, request }) => {
  test.skip(!fs.existsSync(credentialsPath), "Run the development demo seed first");
  const credentials = JSON.parse(fs.readFileSync(credentialsPath, "utf8"));
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const denied = await request.get("http://localhost:3000/api/forms-proxy");
  expect(denied.status()).toBe(401);
  await page.goto("http://localhost:3000/forms");
  await page.getByLabel("Jeton d’accès").fill(credentials.token);
  await page.getByRole("button", { name: "Charger les formulaires" }).click();
  await page.getByRole("button", { name: "Rapport quotidien territorial", exact: true }).click();
  await page.getByRole("button", { name: /^v\d+ · PUBLISHED$/ }).last().click();
  await page.getByLabel(/Date du rapport/).fill("2026-09-28");
  await page.getByLabel(/Niveau de situation/).selectOption({ label: "Normal" });
  await page.getByLabel(/Résumé de la journée/).fill("Les activités territoriales se sont déroulées normalement.");
  await page.getByRole("button", { name: "Ajouter — Activités et faits rapportés" }).click();
  await page.getByLabel(/Catégorie/).selectOption({ label: "Activité de terrain" });
  await page.getByLabel("Description *", { exact: true }).fill("Visite de terrain");
  await page.getByLabel(/Date et heure/).fill("2026-09-28T08:30");
  await page.getByLabel(/Quantité/).fill("3");
  await page.getByLabel(/Je confirme/).check();
  await page.getByRole("button", { name: "Vérifier les réponses" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Vérification serveur" })).toContainText("Les réponses sont valides");
  await page.getByLabel(/Un appui supérieur/).check();
  await expect(page.getByLabel("Appui demandé")).toBeVisible();
  await page.getByRole("button", { name: "Vérifier les réponses" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Vérification serveur" })).toContainText("à corriger");
  await page.getByLabel("Appui demandé").fill("Besoin de matériel supplémentaire.");
  await page.getByLabel("Langue").selectOption("ar");
  await expect(page.locator("form.dynamic-form")).toHaveAttribute("dir", "rtl");
  await expect(page.getByLabel(/ملخص اليوم/)).toHaveValue("Les activités territoriales se sont déroulées normalement.");
  await page.getByRole("button", { name: "التحقق من الإجابات" }).click();
  await expect(page.getByRole("status").filter({ hasText: "التحقق على الخادم" })).toContainText("الإجابات صحيحة");
  await page.screenshot({ path: "../../.local/forms-ar.png", fullPage: true });
  await page.getByLabel("Langue").selectOption("fr");
  await page.screenshot({ path: "../../.local/forms-fr.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator("body")).toHaveJSProperty("scrollWidth", 390);
  await page.screenshot({ path: "../../.local/forms-mobile.png", fullPage: true });
  expect(errors).toEqual([]);
});
