import { expect, test } from "@playwright/test";
import path from "node:path";

const base = "http://localhost:3001";

test("isolated PostGIS map respects scope and works on mobile in EN, FR and AR", async ({ browser }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  const centralContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const central = await centralContext.newPage();
  central.on("pageerror", error => errors.push(error.message));
  await central.goto(base + "/map");
  await central.locator("#app-language").selectOption("en");
  await central.locator('[data-account="central"]').click();
  await expect(central.getByRole("heading", { name: "Report map" })).toBeVisible();
  await expect(central.getByText("Visible points : 2 / 2")).toBeVisible({ timeout: 30000 });
  await expect(central.locator(".leaflet-interactive")).toHaveCount(2);
  const formFilter = central.getByLabel("Form");
  const selectedForm = await formFilter.locator("option").nth(1).getAttribute("value");
  expect(selectedForm).toBeTruthy();
  await central.getByLabel("From", { exact: true }).fill("2026-09-28");
  await central.getByLabel("To", { exact: true }).fill("2026-09-28");
  await expect(central.getByText("Visible points : 0 / 0")).toBeVisible({ timeout: 30000 });
  await expect(formFilter.locator("option")).toHaveCount(2);
  await formFilter.selectOption(selectedForm!);
  await expect(central.getByText("Visible points : 0 / 0")).toBeVisible();
  await expect(formFilter).toHaveValue(selectedForm!);
  await central.getByLabel("From", { exact: true }).fill("2026-09-29");
  await central.getByLabel("To", { exact: true }).fill("2026-09-29");
  await expect(central.getByText("Visible points : 2 / 2")).toBeVisible({ timeout: 30000 });
  await central.locator(".leaflet-interactive").first().click();
  await expect(central.locator(".leaflet-popup-content a")).toHaveText("View report");
  await central.locator(".leaflet-popup-content a").click();
  await expect(central.getByRole("heading", { name: /Revision 1/ })).toBeVisible({ timeout: 30000 });
  await central.getByRole("button", { name: "Open menu" }).click();
  await central.getByRole("navigation").getByRole("link", { name: "Report map" }).click();
  await expect(central.getByText("Visible points : 2 / 2")).toBeVisible({ timeout: 30000 });
  await central.screenshot({ path: path.resolve("../../.local/phase8c-isolated-map-en.png"), fullPage: true });
  await central.locator("#app-language").selectOption("ar");
  await expect(central.locator("html")).toHaveAttribute("dir", "rtl");
  await expect(central.getByRole("heading", { level: 1, name: "خريطة التقارير" })).toBeVisible();
  expect(await central.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await central.screenshot({ path: path.resolve("../../.local/phase8c-isolated-map-ar.png"), fullPage: true });

  const reviewerContext = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const reviewer = await reviewerContext.newPage();
  reviewer.on("pageerror", error => errors.push(error.message));
  await reviewer.goto(base + "/map");
  await reviewer.locator('[data-account="reviewer"]').click();
  await expect(reviewer.getByText("Points visibles : 2 / 2")).toBeVisible({ timeout: 30000 });
  expect(await reviewer.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await reviewer.screenshot({ path: path.resolve("../../.local/phase8c-isolated-map-fr-desktop.png"), fullPage: true });
  const foreignContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const foreign = await foreignContext.newPage();
  foreign.on("pageerror", error => errors.push(error.message));
  await foreign.goto(base + "/map");
  await foreign.locator('[data-account="other_wilaya"]').click();
  await expect(foreign.getByText("Aucun point GPS dans cette période et ce périmètre.")).toBeVisible({ timeout: 30000 });
  expect(await foreign.locator(".leaflet-interactive").count()).toBe(0);
  expect(errors).toEqual([]);
  await centralContext.close(); await reviewerContext.close(); await foreignContext.close();
});
