import type { Locale } from "../forms/types";

// French is the source key; English and Arabic cover the application vocabulary.
const rows: [string, string, string][] = [
  ["Carte des rapports", "Report map", "خريطة التقارير"],
  ["Positions GPS des activités confirmées", "GPS positions of confirmed activities", "مواقع أنشطة التقارير المؤكدة"],
  ["Points visibles", "Visible points", "النقاط الظاهرة"],
  ["Points accessibles", "Accessible points", "النقاط المتاحة"],
  ["Aucun point GPS dans cette période et ce périmètre.", "No GPS points in this period and scope.", "لا توجد نقاط GPS في هذه الفترة وهذا النطاق."],
  ["Affichage limité à 500 points. Réduisez la période ou choisissez un territoire.", "Display limited to 500 points. Narrow the period or choose a territory.", "العرض محدود بـ500 نقطة. قلّص الفترة أو اختر منطقة."],
  ["Coordonnées GPS", "GPS coordinates", "إحداثيات GPS"],
  ["Voir le rapport", "View report", "عرض التقرير"],
  ["Activité", "Activity", "نشاط"],
  ["Seule la révision courante de chaque rapport apparaît sur la carte.", "Only the current revision of each report appears on the map.", "تظهر النسخة الحالية فقط من كل تقرير على الخريطة."],
  ["Pilotage", "Analytics", "التحليلات"],
  ["Obligations de reporting et réceptions officielles", "Reporting obligations and official receipts", "التزامات التقارير والإيصالات الرسمية"],
  ["Filtres", "Filters", "المرشحات"],
  ["Indicateurs", "Indicators", "المؤشرات"],
  ["Calculé le", "Calculated at", "حُسب في"],
  ["Évolution par période", "Trend by period", "التطور حسب الفترة"],
  ["Répartition des obligations par période", "Obligations by period", "توزيع الالتزامات حسب الفترة"],
  ["Comparaison territoriale", "Territorial comparison", "مقارنة المناطق"],
  ["Aucune obligation dans cette période et ce périmètre.", "No obligations in this period and scope.", "لا توجد التزامات في هذه الفترة وهذا النطاق."],
  ["Chaque obligation est comptée une seule fois. Une révision ne crée pas de nouvelle réception.", "Each obligation is counted once. A revision does not create another receipt.", "يُحسب كل التزام مرة واحدة. لا تُنشئ المراجعة إيصالاً جديداً."],
  ["Voir les obligations détaillées", "View detailed obligations", "عرض الالتزامات المفصلة"],
  ["Période invalide (maximum 365 jours).", "Invalid period (maximum 365 days).", "فترة غير صالحة (365 يوماً كحد أقصى)."],
  ["Brouillon inaccessible.", "Draft unavailable.", "المسودة غير متاحة."],
  ["Formulaire indisponible.", "Form unavailable.", "النموذج غير متاح."],
  ["Cette version n’est plus disponible pour un nouveau brouillon.", "This version is no longer available for a new draft.", "هذا الإصدار لم يعد متاحاً لإنشاء مسودة جديدة."],
  ["Le fichier doit faire entre 1 octet et 10 Mio.", "The file must be between 1 byte and 10 MiB.", "يجب أن يتراوح حجم الملف بين بايت واحد و10 ميبيبايت."],
  ["Le nom du fichier est trop long.", "The file name is too long.", "اسم الملف طويل جداً."],
  ["Texte Unicode non canonique.", "The text cannot be confirmed. Correct the unsupported characters.", "لا يمكن تأكيد النص. صحّح الرموز غير المدعومة."],
  ["Nombre non canonique.", "The number cannot be confirmed. Use a supported value.", "لا يمكن تأكيد الرقم. استخدم قيمة مدعومة."],
  ["Valeur non canonique.", "The value cannot be confirmed. Check the report.", "لا يمكن تأكيد القيمة. تحقق من التقرير."],
  ["Identité incohérente pour l’inbox.", "Inbox identity mismatch. Sign in again.", "هوية الوارد غير متطابقة. سجّل الدخول مجدداً."],
  ["Inbox hors périmètre.", "Inbox outside your authorized scope.", "الوارد خارج نطاق صلاحياتك."],
  ["Version d’origine indisponible.", "Original version unavailable.", "الإصدار الأصلي غير متاح."],
  ["Intégrité de pièce jointe incorrecte.", "Attachment integrity check failed.", "فشل التحقق من سلامة المرفق."],
  ["Réauthentification requise pour créer un brouillon.", "Sign in again to create a draft.", "سجّل الدخول مجدداً لإنشاء مسودة."],
  ["Session locale expirée. Les réponses restent visibles et exportables.", "Local session expired. Answers remain readable and exportable.", "انتهت الجلسة المحلية. يمكن قراءة الإجابات وتصديرها."],
  ["Rapport figé. Revenez au brouillon avant de modifier.", "Report frozen. Return to draft before editing.", "التقرير مُثبّت. عُد إلى المسودة قبل التعديل."],
  ["Ce brouillon a changé dans un autre onglet. Exportez vos réponses avant de le rouvrir.", "This draft changed in another tab. Export your answers before reopening it.", "تغيّرت المسودة في علامة تبويب أخرى. صدّر إجاباتك قبل إعادة فتحها."],
  ["Une opération attend son accusé. Dupliquez le brouillon pour continuer.", "An operation is awaiting its receipt. Duplicate the draft to continue.", "عملية بانتظار إقرارها. أنشئ نسخة من المسودة للمتابعة."],
  ["Réauthentification requise.", "Sign in again.", "سجّل الدخول مجدداً."],
  ["Accusé serveur incohérent.", "Inconsistent server receipt.", "إقرار الخادم غير متسق."],
  ["Format accepté : JPEG, PNG ou PDF.", "Accepted formats: JPEG, PNG or PDF.", "الصيغ المقبولة: JPEG أو PNG أو PDF."],
  ["Ce brouillon a changé dans un autre onglet.", "This draft changed in another tab.", "تغيّرت المسودة في علامة تبويب أخرى."],
  ["Session locale expirée.", "Local session expired.", "انتهت الجلسة المحلية."],
  ["Pièce jointe inaccessible.", "Attachment unavailable.", "المرفق غير متاح."],
  ["Rapport figé.", "Report frozen.", "التقرير مُثبّت."],
  ["Le brouillon a changé ou attend un accusé.", "The draft changed or is awaiting a receipt.", "تغيّرت المسودة أو هي بانتظار إقرار."],
  ["Une pièce déjà reçue ne peut pas être retirée du brouillon.", "An already received attachment cannot be removed from the draft.", "لا يمكن إزالة مرفق تم استلامه من المسودة."],
  ["Réauthentification requise pour finaliser.", "Sign in again to finalize.", "سجّل الدخول مجدداً لإكمال التقرير."],
  ["Ce rapport est déjà confirmé.", "This report is already confirmed.", "تم تأكيد هذا التقرير بالفعل."],
  ["Attendez la sauvegarde ou l’accusé du brouillon avant de finaliser.", "Wait for the draft to be saved or acknowledged before finalizing.", "انتظر حفظ المسودة أو إقرارها قبل الإكمال."],
  ["Réponses à corriger", "Answers need correction", "إجابات تحتاج إلى تصحيح"],
  ["Préparez votre session en ligne pour obtenir les droits de confirmation.", "Prepare your session online to obtain confirmation permissions.", "أعدّ جلستك عبر الإنترنت للحصول على صلاحيات التأكيد."],
  ["Seul un rapport finalisé peut revenir en brouillon.", "Only a finalized report can return to draft.", "يمكن إعادة التقرير المكتمل فقط إلى مسودة."],
  ["Réauthentification requise pour confirmer.", "Sign in again to confirm.", "سجّل الدخول مجدداً للتأكيد."],
  ["Finalisez les réponses avant la confirmation.", "Finalize answers before confirmation.", "أكمل الإجابات قبل التأكيد."],
  ["Contexte de confirmation expiré ou incohérent. Préparez votre session puis finalisez à nouveau.", "Confirmation context expired or inconsistent. Prepare your session, then finalize again.", "انتهى سياق التأكيد أو هو غير متسق. أعدّ جلستك ثم أكمل التقرير مجدداً."],
  ["Les pièces jointes ne correspondent pas aux fichiers locaux.", "Attachments do not match the local files.", "المرفقات لا تطابق الملفات المحلية."],
  ["Le brouillon a changé pendant la confirmation.", "The draft changed during confirmation.", "تغيّرت المسودة أثناء التأكيد."],
  ["Accusé de rapport incohérent.", "Inconsistent report receipt.", "إقرار التقرير غير متسق."],
  ["Accusé de pièce jointe incohérent.", "Inconsistent attachment receipt.", "إقرار المرفق غير متسق."],
  ["Préparation de la session refusée.", "Session preparation rejected.", "رُفض إعداد الجلسة."],
  ["Préparez votre session en ligne avant de corriger.", "Prepare your session online before correcting.", "أعدّ جلستك عبر الإنترنت قبل التصحيح."],
  ["Cette correction n’a pas été préparée sur cet appareil.", "This correction has not been prepared on this device.", "لم يُعدّ هذا التصحيح على هذا الجهاز."],
  ["Ce navigateur ne permet pas le démarrage hors ligne.", "This browser does not support offline startup.", "هذا المتصفح لا يدعم بدء التشغيل دون اتصال."],
  ["Préparation hors ligne incomplète. Réessayez en ligne.", "Offline preparation incomplete. Retry online.", "إعداد الوضع دون اتصال غير مكتمل. أعد المحاولة عبر الإنترنت."],
  ["Préparation de l’inbox hors ligne interrompue.", "Offline inbox preparation interrupted.", "انقطع إعداد الوارد دون اتصال."],
  ["Filtres", "Filters", "الفلاتر"],
  ["Aucun rapport sélectionné.", "No report selected.", "لم يتم اختيار تقرير."],
  ["Les données ont changé. Actualisez puis réessayez. Votre copie reste conservée.", "Data changed. Refresh and retry. Your copy is retained.", "تغيّرت البيانات. حدّث وأعد المحاولة. نسختك محفوظة."],
  ["Ce formulaire n’est plus disponible. Vos données sont conservées.", "This form is no longer available. Your data is retained.", "هذا النموذج لم يعد متاحاً. بياناتك محفوظة."],
  ["Pièce jointe trop volumineuse.", "Attachment too large.", "المرفق كبير جداً."],
  ["Connexion impossible. Vérifiez le réseau puis réessayez.", "Unable to connect. Check your network and retry.", "تعذر الاتصال. تحقق من الشبكة وأعد المحاولة."],
  ["Oui", "Yes", "نعم"],
  ["Non", "No", "لا"],
  ["Fin de session locale", "Local session ends", "نهاية الجلسة المحلية"],
  ["Historique et commentaires", "History and comments", "السجل والتعليقات"],
  ["Accusé serveur reçu avant ou à l’échéance", "Server receipt at or before the deadline", "استُلم إقرار الخادم قبل الموعد النهائي أو فيه"],
  ["Accusé serveur reçu après l’échéance", "Server receipt after the deadline", "استُلم إقرار الخادم بعد الموعد النهائي"],
  ["Échéance dépassée sans accusé serveur lié", "Deadline passed without a linked server receipt", "انتهى الموعد دون إقرار خادم مرتبط"],
  ["Échéance à venir, aucun accusé serveur lié", "Upcoming deadline, no linked server receipt", "الموعد قادم ولا يوجد إقرار خادم مرتبط"],
  ["Session de correction expirée. Les demandes restent conservées.", "Correction session expired. Requests are retained.", "انتهت جلسة التصحيح. الطلبات محفوظة."],
  ["Contexte de correction incohérent.", "Inconsistent correction context.", "سياق التصحيح غير متسق."],
  ["Pièces jointes non préparées.", "Attachments are not prepared.", "المرفقات غير جاهزة."],
  ["Pièce jointe locale altérée.", "Local attachment is corrupted.", "المرفق المحلي تالف."],
  ["SELF", "Territory only", "المنطقة فقط"],
  ["DESCENDANTS", "Territory and descendants", "المنطقة والمناطق التابعة"],
  ["AUTHOR", "Author", "المؤلف"],
  ["REVIEWER", "Reviewer", "المراجع"],
  ["CENTRAL", "Central reader", "القارئ المركزي"],
  ["ADMIN", "Administrator", "المسؤول الإداري"],
  ["Date du rapport", "Report date", "تاريخ التقرير"],
  ["Niveau de situation", "Situation level", "مستوى الوضع"],
  ["Normal", "Normal", "عادي"],
  ["Vigilance", "Watch", "يقظة"],
  ["Critique", "Critical", "حرج"],
  ["Résumé de la journée", "Daily summary", "ملخص اليوم"],
  ["Activités et faits rapportés", "Reported activities and events", "الأنشطة والوقائع المبلغ عنها"],
  ["Catégorie", "Category", "الفئة"],
  ["Description", "Description", "الوصف"],
  ["Date et heure", "Date and time", "التاريخ والوقت"],
  ["Quantité", "Quantity", "الكمية"],
  ["Unité", "Unit", "الوحدة"],
  ["Position GPS", "GPS position", "الموقع الجغرافي"],
  ["Latitude", "Latitude", "خط العرض"],
  ["Longitude", "Longitude", "خط الطول"],
  ["Précision en mètres", "Accuracy in meters", "الدقة بالأمتار"],
  ["Difficultés rencontrées", "Difficulties encountered", "الصعوبات التي تمت مواجهتها"],
  ["Un appui supérieur est-il demandé ?", "Is support from a higher level requested?", "هل تم طلب دعم من المستوى الأعلى؟"],
  ["Appui demandé", "Requested support", "الدعم المطلوب"],
  ["Pièces jointes", "Attachments", "المرفقات"],
  ["Identifiant de la pièce jointe", "Attachment identifier", "معرف المرفق"],
  ["Nom du fichier", "File name", "اسم الملف"],
  ["Type de fichier", "File type", "نوع الملف"],
  ["Taille en octets", "Size in bytes", "الحجم بالبايت"],
  ["Empreinte SHA-256", "SHA-256 fingerprint", "بصمة SHA-256"],
  ["Je confirme l'exactitude des informations fournies.", "I confirm the accuracy of the information provided.", "أؤكد صحة المعلومات المقدمة."],
  ["Rapport quotidien territorial", "Daily territorial report", "التقرير الإقليمي اليومي"],
  ["Formulaire pilote configurable pour démontrer la collecte quotidienne hors ligne et la remontée hiérarchique.", "Configurable pilot form for offline daily collection and hierarchical reporting.", "نموذج تجريبي قابل للتهيئة لإثبات الجمع اليومي دون اتصال والتسلسل الإداري."],
  ["Administration", "Administration", "الإدارة"],
  ["Service public", "Public service", "الخدمة العامة"],
  ["Activité de terrain", "Field activity", "نشاط ميداني"],
  ["Incident", "Incident", "حادث"],
  ["Autre", "Other", "أخرى"],
  ["NATIONAL", "National", "وطني"], ["WILAYA", "Region", "ولاية"], ["MOUGHATAA", "District", "مقاطعة"], ["COMMUNE", "Commune", "بلدية"],
  ["Publié", "Published", "منشور"], ["Retiré", "Withdrawn", "مسحوب"],
  ["Accueil", "Home", "الرئيسية"], ["Collecte", "Collection", "جمع البيانات"],
  ["Nouveau rapport", "New report", "تقرير جديد"], ["Brouillons", "Drafts", "المسودات"],
  ["Mes rapports", "My reports", "تقاريري"], ["Rapports", "Reports", "التقارير"],
  ["Inbox", "Inbox", "الوارد"], ["Corrections", "Corrections", "التصحيحات"],
  ["Formulaires", "Forms", "النماذج"], ["Administration", "Administration", "الإدارة"],
  ["Utilisateurs", "Users", "المستخدمون"], ["Organisations", "Organizations", "المؤسسات"],
  ["Territoires", "Territories", "المناطق"], ["Profil", "Profile", "الملف الشخصي"],
  ["Langue", "Language", "اللغة"], ["Navigation", "Navigation", "التنقل"],
  ["Ouvrir le menu", "Open menu", "فتح القائمة"], ["Fermer le menu", "Close menu", "إغلاق القائمة"],
  ["Aller au contenu", "Skip to content", "الانتقال إلى المحتوى"],
  ["Connecté", "Signed in", "متصل"], ["Se connecter", "Sign in", "تسجيل الدخول"],
  ["Se déconnecter", "Sign out", "تسجيل الخروج"], ["Connexion", "Sign in", "تسجيل الدخول"],
  ["Session requise", "Sign in required", "يلزم تسجيل الدخول"],
  ["Connectez-vous pour accéder à votre espace.", "Sign in to access your workspace.", "سجّل الدخول للوصول إلى مساحة عملك."],
  ["Pilote local", "Local pilot", "التجربة المحلية"],
  ["Comptes de démonstration", "Demo accounts", "حسابات تجريبية"],
  ["Ces comptes utilisent uniquement les données synthétiques du pilote local.", "These accounts use only synthetic local pilot data.", "تستخدم هذه الحسابات بيانات تجريبية محلية فقط."],
  ["Auteur communal", "Local author", "المؤلف المحلي"], ["Responsable territorial", "Territorial reviewer", "المسؤول الإقليمي"],
  ["Responsable régional", "Regional reviewer", "المسؤول الجهوي"], ["Lecteur central", "Central reader", "القارئ المركزي"],
  ["Autre Wilaya", "Other region", "ولاية أخرى"], ["Administrateur", "Administrator", "المسؤول الإداري"],
  ["Connexion avancée", "Advanced sign in", "تسجيل دخول متقدم"], ["Jeton d’accès", "Access token", "رمز الوصول"],
  ["Identifiant", "Username", "اسم المستخدم"], ["Mot de passe", "Password", "كلمة المرور"],
  ["Identifiant ou mot de passe incorrect.", "Incorrect username or password.", "اسم المستخدم أو كلمة المرور غير صحيحين."],
  ["ROOT", "Root scope", "النطاق الرئيسي"],
  ["Le jeton reste uniquement en mémoire pendant cette session.", "The token stays only in memory during this session.", "يبقى الرمز في الذاكرة فقط خلال هذه الجلسة."],
  ["La connexion de démonstration n’est pas disponible.", "Demo sign in is unavailable.", "تسجيل الدخول التجريبي غير متاح."],
  ["En ligne", "Online", "متصل بالإنترنت"], ["Hors connexion", "Offline", "غير متصل"],
  ["Réseau", "Network", "الشبكة"], ["Synchronisation", "Synchronization", "المزامنة"],
  ["À jour", "Up to date", "محدّث"], ["À synchroniser", "Awaiting sync", "بانتظار المزامنة"],
  ["Synchroniser maintenant", "Sync now", "مزامنة الآن"], ["Synchronisation en cours…", "Syncing…", "جارٍ المزامنة…"],
  ["Données conservées sur cet appareil", "Data kept on this device", "البيانات محفوظة على هذا الجهاز"],
  ["Session expirée, reconnectez-vous.", "Session expired. Sign in again.", "انتهت الجلسة. سجّل الدخول مجدداً."],
  ["Dernière synchronisation", "Last synchronization", "آخر مزامنة"], ["Bloqués", "Blocked", "محظورة"],
  ["Données en attente : reconnectez-vous pour les envoyer.", "Pending data: sign in to send it.", "بيانات معلّقة: سجّل الدخول لإرسالها."],
  ["Votre espace de travail", "Your workspace", "مساحة عملك"],
  ["Des informations fiables du terrain à la décision.", "Reliable information from the field to decisions.", "معلومات موثوقة من الميدان إلى القرار."],
  ["Collecter. Synchroniser. Agir. Ensemble.", "Collect. Sync. Act. Together.", "نجمع. نزامن. نعمل. معاً."],
  ["Corrections demandées", "Requested corrections", "التصحيحات المطلوبة"],
  ["Rapports accessibles", "Accessible reports", "التقارير المتاحة"],
  ["Actualiser", "Refresh", "تحديث"], ["Chargement…", "Loading…", "جارٍ التحميل…"],
  ["Aucune donnée disponible.", "No data available.", "لا توجد بيانات متاحة."],
  ["Accès non autorisé", "Access denied", "الوصول غير مسموح"],
  ["Vos droits ne permettent pas cette action.", "Your permissions do not allow this action.", "صلاحياتك لا تسمح بهذا الإجراء."],
  ["Données serveur indisponibles hors connexion.", "Server data is unavailable offline.", "بيانات الخادم غير متاحة دون اتصال."],
  ["Réessayer", "Retry", "إعادة المحاولة"], ["Opération impossible.", "Unable to complete the operation.", "تعذر إتمام العملية."],
  ["Opération interrompue.", "Operation interrupted.", "انقطعت العملية."], ["Erreur inattendue", "Unexpected error", "خطأ غير متوقع"],
  ["Fermer", "Close", "إغلاق"], ["Notifications", "Notifications", "الإشعارات"],
  ["Aucune notification.", "No notifications.", "لا توجد إشعارات."],
  ["Organisation", "Organization", "المؤسسة"], ["Territoire", "Territory", "المنطقة"],
  ["Auteur", "Author", "المؤلف"], ["Formulaire", "Form", "النموذج"],
  ["Affectations actives", "Active assignments", "التكليفات النشطة"], ["Rôle", "Role", "الدور"],
  ["Niveau d’habilitation", "Clearance level", "مستوى الصلاحية"], ["Périmètre", "Scope", "النطاق"],
  ["Territoire et descendants", "Territory and descendants", "المنطقة والمناطق التابعة"],
  ["Territoire uniquement", "Territory only", "المنطقة فقط"],
  ["Annuaire en lecture seule", "Read-only directory", "دليل للقراءة فقط"],
  ["Les données affichées sont limitées à votre périmètre autorisé.", "Displayed data is limited to your authorized scope.", "البيانات المعروضة محدودة بنطاق صلاحياتك."],
  ["Nom", "Name", "الاسم"], ["Code", "Code", "الرمز"], ["Type", "Type", "النوع"],
  ["Catalogue", "Catalog", "الفهرس"], ["Aucun formulaire accessible.", "No accessible forms.", "لا توجد نماذج متاحة."],
  ["Nouveau formulaire", "New form", "نموذج جديد"], ["Créer", "Create", "إنشاء"],
  ["Sélectionnez un formulaire.", "Select a form.", "اختر نموذجاً."],
  ["Importer une nouvelle version JSON", "Import a new JSON version", "استيراد إصدار JSON جديد"],
  ["Définition du formulaire", "Form definition", "تعريف النموذج"], ["Charger un fichier JSON", "Load a JSON file", "تحميل ملف JSON"],
  ["Créer le brouillon", "Create draft", "إنشاء المسودة"], ["Publier", "Publish", "نشر"], ["Retirer", "Withdraw", "سحب"],
  ["Copier la définition pour une nouvelle version", "Copy definition for a new version", "نسخ التعريف لإصدار جديد"],
  ["Définir, publier et vérifier les formulaires de votre organisation.", "Define, publish and check your organization's forms.", "تعريف نماذج مؤسستك ونشرها والتحقق منها."],
  ["Charger les formulaires", "Load forms", "تحميل النماذج"], ["Identifiant du territoire", "Territory identifier", "معرّف المنطقة"],
  ["Collecte hors ligne", "Offline collection", "جمع البيانات دون اتصال"],
  ["Connexion disponible", "Connection available", "الاتصال متاح"],
  ["Application préparée pour le hors-ligne", "App ready for offline use", "التطبيق جاهز للعمل دون اتصال"],
  ["Préparation du mode hors ligne…", "Preparing offline mode…", "إعداد الوضع دون اتصال…"],
  ["Enregistrez un brouillon, finalisez les réponses puis confirmez explicitement le rapport.", "Save a draft, finalize the answers, then explicitly confirm the report.", "احفظ مسودة وأكمل الإجابات ثم أكّد التقرير صراحةً."],
  ["Préparer mes formulaires", "Prepare my forms", "إعداد نماذجي"],
  ["Mes brouillons", "My drafts", "مسوداتي"], ["Nouveau brouillon", "New draft", "مسودة جديدة"],
  ["Aucun brouillon sur cet appareil.", "No drafts on this device.", "لا توجد مسودات على هذا الجهاز."],
  ["Créez ou ouvrez un brouillon. Chaque modification est enregistrée sur cet appareil.", "Create or open a draft. Each change is saved on this device.", "أنشئ مسودة أو افتحها. يُحفظ كل تعديل على هذا الجهاز."],
  ["La session locale a expiré. Vous pouvez lire et exporter vos brouillons ; reconnectez-vous pour les modifier.", "The local session has expired. You can read and export drafts; sign in to edit them.", "انتهت الجلسة المحلية. يمكنك قراءة المسودات وتصديرها؛ سجّل الدخول لتعديلها."],
  ["Exporter une copie JSON", "Export a JSON copy", "تصدير نسخة JSON"], ["Enregistrement local…", "Saving locally…", "جارٍ الحفظ محلياً…"],
  ["Enregistré sur cet appareil", "Saved on this device", "محفوظ على هذا الجهاز"],
  ["En attente d’envoi", "Awaiting upload", "بانتظار الإرسال"], ["Envoi en cours", "Uploading", "جارٍ الإرسال"],
  ["Reçu par le serveur", "Received by server", "استلمه الخادم"], ["Envoi à réessayer", "Upload needs retry", "يجب إعادة الإرسال"],
  ["Envoi bloqué — données conservées", "Upload blocked — data retained", "الإرسال محظور — البيانات محفوظة"],
  ["Conflit — données conservées", "Conflict — data retained", "تعارض — البيانات محفوظة"],
  ["Fichiers conservés sur cet appareil", "Files kept on this device", "الملفات محفوظة على هذا الجهاز"],
  ["Ajouter une pièce jointe", "Add attachment", "إضافة مرفق"],
  ["Mettre en attente d’envoi", "Queue for upload", "إضافة إلى قائمة الإرسال"],
  ["Dupliquer pour continuer", "Duplicate to continue", "إنشاء نسخة للمتابعة"],
  ["Aucun écrasement automatique. Exportez votre copie ou dupliquez-la sous un nouvel identifiant.", "No automatic overwrite. Export your copy or duplicate it under a new identifier.", "لا يُستبدل المحتوى تلقائياً. صدّر نسختك أو أنشئ نسخة بمعرّف جديد."],
  ["Dernier accusé serveur", "Last server receipt", "آخر إقرار من الخادم"],
  ["réponses valides", "valid answers", "إجابات صحيحة"], ["brouillon reçu, réponses à compléter", "draft received, answers incomplete", "استُلمت المسودة، الإجابات غير مكتملة"],
  ["Confirmation du rapport", "Report confirmation", "تأكيد التقرير"], ["État métier", "Report status", "حالة التقرير"],
  ["Brouillon", "Draft", "مسودة"], ["Finalisé", "Finalized", "مكتمل"], ["Confirmé", "Confirmed", "مؤكد"],
  ["Finaliser le rapport", "Finalize report", "إكمال التقرير"],
  ["La confirmation fige les réponses, les fichiers et votre affectation. Relisez le rapport avant de confirmer.", "Confirmation freezes the answers, files and your assignment. Review the report before confirming.", "يُثبّت التأكيد الإجابات والملفات وتكليفك. راجع التقرير قبل التأكيد."],
  ["J’ai relu ce rapport et je confirme son contenu.", "I have reviewed this report and confirm its content.", "راجعت هذا التقرير وأؤكد محتواه."],
  ["Confirmer définitivement", "Confirm permanently", "تأكيد نهائي"], ["Revenir au brouillon", "Return to draft", "العودة إلى المسودة"],
  ["Rapport reçu par le serveur", "Report received by server", "استلم الخادم التقرير"],
  ["Rapport bloqué — copie conservée", "Report blocked — copy retained", "التقرير محظور — النسخة محفوظة"],
  ["Rapport à réessayer", "Report needs retry", "يجب إعادة إرسال التقرير"],
  ["Rapport confirmé — en attente de réception", "Report confirmed — awaiting receipt", "التقرير مؤكد — بانتظار الاستلام"],
  ["Empreinte SHA‑256", "SHA-256 fingerprint", "بصمة SHA-256"], ["Accusé serveur", "Server receipt", "إقرار الخادم"],
  ["La confirmation conserve une preuve technique d’intégrité et d’attribution.", "Confirmation retains technical proof of integrity and attribution.", "يحتفظ التأكيد بدليل تقني على سلامة المحتوى ونسبته إلى مؤلفه."],
  ["Rapports confirmés", "Confirmed reports", "التقارير المؤكدة"], ["Charger les rapports", "Load reports", "تحميل التقارير"],
  ["Aucun rapport chargé.", "No reports loaded.", "لم تُحمّل تقارير."], ["Rapport", "Report", "تقرير"],
  ["Révision", "Revision", "مراجعة"], ["Remplacée", "Superseded", "مستبدلة"], ["Confirmée", "Confirmed", "مؤكدة"],
  ["Confirmé le", "Confirmed on", "تم التأكيد في"], ["Télécharger", "Download", "تنزيل"],
  ["Commentaires", "Comments", "التعليقات"], ["Commentaire", "Comment", "تعليق"],
  ["Motif de correction", "Reason for correction", "سبب التصحيح"],
  ["Réessayer le même envoi", "Retry the same submission", "إعادة المحاولة بنفس الإرسال"],
  ["Ajouter le commentaire", "Add comment", "إضافة تعليق"], ["Demander une correction", "Request correction", "طلب تصحيح"],
  ["Correction", "Correction", "تصحيح"], ["résolue", "resolved", "تم حلّه"], ["demandée", "requested", "مطلوب"],
  ["Préparer la nouvelle révision", "Prepare new revision", "إعداد مراجعة جديدة"],
  ["Accusé incohérent. L’opération reste conservée.", "Inconsistent receipt. The operation is retained.", "الإقرار غير متسق. العملية محفوظة."],
  ["Envoi interrompu.", "Submission interrupted.", "انقطع الإرسال."],
  ["Inbox et obligations de reporting", "Inbox and reporting obligations", "الوارد والتزامات التقارير"],
  ["Mes rapports et corrections", "My reports and corrections", "تقاريري وتصحيحاتي"],
  ["Inbox hiérarchique", "Hierarchical inbox", "الوارد الهرمي"], ["Vue", "View", "العرض"], ["Statut", "Status", "الحالة"],
  ["Tous", "All", "الكل"], ["Du", "From", "من"], ["Au", "To", "إلى"],
  ["Synchroniser mon inbox", "Sync my inbox", "مزامنة الوارد"], ["Rapports reçus", "Received reports", "التقارير المستلمة"],
  ["À examiner", "To review", "بانتظار المراجعة"], ["Correction demandée", "Correction requested", "تصحيح مطلوب"],
  ["Corrigés", "Corrected", "مصَحّحة"], ["Confirmés", "Confirmed", "مؤكدة"], ["Attendus", "Expected", "متوقعة"],
  ["Manquants", "Missing", "ناقصة"], ["Reçus en retard", "Received late", "استُلمت متأخرة"],
  ["À resynchroniser", "Awaiting resync", "بانتظار إعادة المزامنة"],
  ["Consulter et commenter", "View and comment", "عرض وإضافة تعليق"], ["Marquer comme examiné", "Mark as reviewed", "وضع علامة تمت المراجعة"],
  ["Dernière récupération", "Last download", "آخر تنزيل"], ["Préparer la correction hors ligne", "Prepare offline correction", "إعداد التصحيح دون اتصال"],
  ["Aucun rapport dans cette vue.", "No reports in this view.", "لا توجد تقارير في هذا العرض."],
  ["Obligations", "Obligations", "الالتزامات"], ["Reçus à temps", "Received on time", "استُلمت في الموعد"],
  ["À venir", "Upcoming", "قادمة"], ["Période", "Period", "الفترة"], ["Échéance", "Deadline", "الموعد النهائي"],
  ["Statut et justification", "Status and reason", "الحالة والسبب"], ["Action", "Action", "الإجراء"],
  ["Remplir le rapport attendu", "Fill expected report", "تعبئة التقرير المتوقع"], ["Reçu", "Received", "مستلم"],
  ["Reçu à temps", "Received on time", "استُلم في الموعد"],
  ["Préparez d’abord les formulaires dans Collecte.", "Prepare the forms in Collection first.", "أعدّ النماذج في صفحة جمع البيانات أولاً."],
  ["Obligation indisponible ou déjà satisfaite.", "Obligation unavailable or already fulfilled.", "الالتزام غير متاح أو تم الوفاء به."],
  ["Synchronisez en ligne pour préparer cette correction.", "Sync online to prepare this correction.", "زامن عبر الإنترنت لإعداد هذا التصحيح."],
  ["Session refusée.", "Session rejected.", "رُفضت الجلسة."], ["Session expirée.", "Session expired.", "انتهت الجلسة."],
  ["Hors connexion — demandes conservées sur cet appareil", "Offline — requests kept on this device", "غير متصل — الطلبات محفوظة على هذا الجهاز"],
  ["Session expirée, réauthentification nécessaire", "Session expired, sign in again", "انتهت الجلسة، يلزم تسجيل الدخول مجدداً"],
  ["Le stockage local est indisponible. Aucune sauvegarde n’est garantie.", "Local storage is unavailable. Saving cannot be guaranteed.", "التخزين المحلي غير متاح. لا يمكن ضمان حفظ البيانات."],
  ["Synchronisation interrompue.", "Synchronization interrupted.", "انقطعت المزامنة."],
  ["Préparation des droits de confirmation interrompue.", "Confirmation permission preparation interrupted.", "انقطع إعداد صلاحيات التأكيد."],
  ["Exportez les réponses non enregistrées avant de changer de brouillon.", "Export unsaved answers before changing drafts.", "صدّر الإجابات غير المحفوظة قبل تغيير المسودة."],
  ["Échec de sauvegarde locale.", "Local save failed.", "فشل الحفظ المحلي."],
  ["Sauvegarde locale non terminée.", "Local save incomplete.", "الحفظ المحلي غير مكتمل."],
  ["Enregistrer", "Save", "حفظ"], ["Version", "Version", "الإصدار"], ["copie serveur", "server copy", "نسخة الخادم"],
  ["le brouillon et son opération restent sur cet appareil.", "the draft and its operation remain on this device.", "تبقى المسودة وعمليتها على هذا الجهاز."],
  ["Contenu du rapport", "Report content", "محتوى التقرير"], ["Historique", "History", "السجل"],
  ["Preuve de confirmation", "Confirmation proof", "دليل التأكيد"],
  ["Droits révoqués ou session expirée. Vos données restent conservées.", "Permissions revoked or session expired. Your data is retained.", "أُلغيت الصلاحيات أو انتهت الجلسة. بياناتك محفوظة."],
  ["Changer le mot de passe", "Change password", "تغيير كلمة المرور"],
  ["La modification nécessite une connexion. Les autres sessions seront fermées.", "An online connection is required. Other sessions will be signed out.", "يتطلب التغيير اتصالاً بالإنترنت. سيتم إنهاء الجلسات الأخرى."],
  ["Mot de passe actuel", "Current password", "كلمة المرور الحالية"],
  ["Nouveau mot de passe", "New password", "كلمة المرور الجديدة"],
  ["Confirmer le nouveau mot de passe", "Confirm new password", "تأكيد كلمة المرور الجديدة"],
  ["Modifier le mot de passe", "Update password", "تحديث كلمة المرور"],
  ["Modification en cours…", "Updating…", "جارٍ التحديث…"],
  ["Les nouveaux mots de passe ne correspondent pas.", "New passwords do not match.", "كلمتا المرور الجديدتان غير متطابقتين."],
  ["Choisissez un nouveau mot de passe différent.", "Choose a different new password.", "اختر كلمة مرور جديدة مختلفة."],
  ["Connectez-vous pour modifier le mot de passe.", "Sign in to change your password.", "سجّل الدخول لتغيير كلمة المرور."],
  ["Mot de passe actuel incorrect.", "Current password is incorrect.", "كلمة المرور الحالية غير صحيحة."],
  ["Le nouveau mot de passe doit contenir au moins 14 caractères et au plus 1 024 octets.", "The new password must have at least 14 characters and at most 1,024 bytes.", "يجب أن تتكون كلمة المرور الجديدة من 14 حرفاً على الأقل وألا تتجاوز 1024 بايت."],
  ["Session expirée. Reconnectez-vous.", "Session expired. Sign in again.", "انتهت الجلسة. سجّل الدخول مجدداً."],
  ["Modification impossible. Réessayez.", "Unable to update password. Try again.", "تعذر تحديث كلمة المرور. حاول مجدداً."],
  ["Mot de passe modifié. Les autres sessions ont été fermées.", "Password updated. Other sessions have been signed out.", "تم تحديث كلمة المرور وإنهاء الجلسات الأخرى."],
];
const dictionary = new Map(rows.map(([fr, en, ar]) => [fr, { fr, en, ar }]));
export function translateUI(text: string, locale: Locale): string {
  const exact = dictionary.get(text)?.[locale]; if (exact) return exact;
  if (statusNames[text]) return translateUI(statusNames[text], locale);
  if (text.startsWith("Réponses à corriger : ")) return translateUI("Réponses à corriger",locale) + " : " + text.slice("Réponses à corriger : ".length);
  if (text.startsWith("Récupération des demandes interrompue")) return translateUI("Synchronisation interrompue.",locale);
  if (/^(Failed to fetch|Load failed|NetworkError)/.test(text)) return translateUI("Connexion impossible. Vérifiez le réseau puis réessayez.",locale);
  if (/^(Rapport inaccessible|Accès refusé|HTTP_40[13]|SESSION_UNAVAILABLE)/.test(text) || /^[A-Z_]+(PERMISSION|UNAUTHORIZED|EXPIRED)[A-Z_]*$/.test(text)) return translateUI("Droits révoqués ou session expirée. Vos données restent conservées.",locale);
  if (/^[A-Z_]+(CONFLICT|CHANGED|REUSED)[A-Z_]*$/.test(text)) return translateUI("Les données ont changé. Actualisez puis réessayez. Votre copie reste conservée.",locale);
  if (/^[A-Z_]*(FORM|VERSION)[A-Z_]*(UNAVAILABLE|RETIRED)[A-Z_]*$/.test(text)) return translateUI("Ce formulaire n’est plus disponible. Vos données sont conservées.",locale);
  if (/^[A-Z_]*(TOO_LARGE|SIZE_LIMIT)[A-Z_]*$/.test(text)) return translateUI("Pièce jointe trop volumineuse.",locale);
  if (/^[A-Z][A-Z0-9_]{3,}$/.test(text) && !["NATIONAL","WILAYA","MOUGHATAA","COMMUNE"].includes(text)) return translateUI("Opération impossible.",locale);
  return text;
}
export const statusNames: Record<string, string> = {
  SUPERSEDED: "Remplacée", LOCAL: "Enregistré sur cet appareil", QUEUED: "En attente d’envoi", SYNCING: "Envoi en cours",
  RECEIVED: "Reçu par le serveur", BLOCKED: "Envoi bloqué — données conservées", ERROR: "Envoi à réessayer",
  CONFLICT: "Conflit — données conservées", DRAFT: "Brouillon", FINALIZED: "Finalisé", CONFIRMED: "Confirmé",
  PUBLISHED: "Publié", RETIRED: "Retiré", TO_REVIEW: "À examiner", CORRECTED: "Corrigés",
  CORRECTION_REQUESTED: "Correction demandée", EXPECTED: "Attendus", MISSING: "Manquants", LATE: "Reçus en retard",
};
